version: '2'
services:
  simplesamlphp-sp:
    build:
      context: ./simplesamlphp-sp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./simplesamlphp-sp/conf:/var/www/conf"
      - "./simplesamlphp-sp/docker-entrypoint.sh:/usr/local/bin/http-foreground"
    container_name: "simplesamlphp-sp"
    entrypoint: /usr/local/bin/http-foreground"
    logging:
      driver: "journald"
