version: '2'
services:
  simplesamlphp-sp:
    build:
      context: ./simplesamlphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config:/var/www/simplesamlphp/config"
      - "./metadata:/var/www/simplesamlphp/metadata"
      - "./simplesamlphp/docker-entrypoint.sh:/usr/local/bin/http-foreground"
    container_name: "simplesamlphp-sp"
    entrypoint: "/usr/local/bin/http-foreground"
    logging:
      driver: "journald"

