version: '2'
services:
  simplesamlphp-idp:
    build: 
      context: ./simplesamlphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf:/var/www/simplesamlphp/conf/"
      - "./simplesamlphp-idp/docker-entrypoint.sh:/http-foreground"
    container_name: "simplesamlphp-idp"
    entrypoint: /usr/local/bin/http-foreground
    logging:
      driver: "journald"
