version: '2'
services:
  simplesamlphp-idp:
    build: 
      context: ./simplesamlphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config:/var/www/simplesamlphp/config"
      - "./metadata:/var/www/simplesamlphp/metadata"
      - "./simplesamlphp-idp/docker-entrypoint.sh:/http-foreground"
    container_name: "simplesamlphp-idp"
    entrypoint: /usr/local/bin/http-foreground
    logging:
      driver: "journald"
